# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, develop, '*/*' ]
  pull_request:
    branches: [ master, develop, '*/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
